apiVersion: v1
kind: Pod
metadata: 
  name: kube-system-proxy
  namespace: kube-system
spec: 
  hostNetwork: true
  containers: 
    - name: "kube-proxy"
      image: "gcr.io/google_containers/hyperkube:v1.1.8" 
      command:
        - "/hyperkube"
        - "proxy"
        - "--master=http://{{ pillar['kube-master'] }}:8080"
        - "--v=2"
      securityContext:
        privileged: true
